### ISSUE TITLE
[Feature Request] Config option to toggle specific nugget drops

### ISSUE THREAD

**Issue by drewbit** [DoctorWiggles/GrimoireOfGaia#7]
Minecraft adds its own gold nuggets and a lot of mods add iron nuggets as well. It would be nice if I could toggle those off in the GoG config.

**Comment by DoctorWiggles** [comment]
Okay so I messed around with it a bit and I've set it up so that the Gaia mobs will drop nuggets and shards from other mods before resorting to dropping Gaia's versions.

I've rolled out the [changes in version 1.4.6 ](https://github.com/DoctorWiggles/GrimoireOfGaia/releases/tag/1.4.0-ALPHA) as seen in bc9f83d

Let me know if that's working out how you had in mind.

For now though the redundant shards are still registered and will show up in creative tabs - they just won't drop from the mobs themselves as long as there are viable alternatives loaded in the game.

**Comment by drewbit** [comment]
Works perfectly, thanks a lot!

**Comment by drewbit** [comment]
Er, I think if multiple types of nugget exists then it just picks one at random and drops it.

For example I have Embers and Immersive Engineering installed, sometimes I'm getting iron nuggets from Embers, sometimes from IE. Unsure if this is even on your end though, maybe I did something dumb.

**Comment by DoctorWiggles** [comment]
It's setup to scan the ore dictionary and use the first registered nugget it finds for each type. 

So as long as you're using the same mods, they _-should-_ register their ores in the same order every time.
But if you add another mod or change them, then the new mods might register theirs first, changing the order and which one it finds first. If you've been testing out the feature and changing out mods every time then that should be what's gong on.

However if the order is getting changed every time you load up the game again with the same exact mods or in the middle of gameplay then I'll have to take a look into what's messing up there  :^)

**Comment by drewbit** [comment]
Sorry for the late reply. I'm pretty sure I'm just blind, everything appears to be working perfect. Thanks!
